/**
 * Use Case data — single source of truth for the Use Case Finder.
 * Each entry mirrors INDEX.md with enriched fields for deal maker matching.
 */

/** The 10 fixed objections deal makers hear from prospects */
export const OBJECTIONS = [
  'Niche market, too specific for online marketing',
  'B2B sector, nobody searches for our services',
  'Our sector is too technical or complex for AI content',
  'Trust-sensitive sector where mistakes are not allowed',
  'We are too small for this kind of approach',
  'We tried it before and it didn\'t work',
  'It takes too long before you see results',
  'Our customers are not online',
  'We get everything from word of mouth',
  'We already do Google Ads, why also SEO',
] as const;

/** Dutch equivalents for bilingual chat matching */
export const OBJECTIONS_NL: Record<Objection, string> = {
  'Niche market, too specific for online marketing': 'niche markt te specifiek online marketing',
  'B2B sector, nobody searches for our services': 'b2b sector niemand zoekt onze diensten',
  'Our sector is too technical or complex for AI content': 'sector te technisch complex ai content',
  'Trust-sensitive sector where mistakes are not allowed': 'vertrouwensgevoelig fouten niet mogen medisch juridisch',
  'We are too small for this kind of approach': 'te klein voor dit soort aanpak',
  'We tried it before and it didn\'t work': 'eerder geprobeerd werkte niet',
  'It takes too long before you see results': 'duurt te lang voordat je iets ziet resultaten',
  'Our customers are not online': 'klanten zitten niet online',
  'We get everything from word of mouth': 'mond-tot-mondreclame mond tot mond',
  'We already do Google Ads, why also SEO': 'google ads waarom ook seo advertenties',
};

export type Objection = typeof OBJECTIONS[number];
export type BusinessType = 'B2B' | 'B2C' | 'Mix';
export type MarketPosition = 'Niche' | 'Mainstream';

export interface UseCase {
  id: string;
  company: string;
  industry: string;
  painPattern: string;
  headline: string;
  outcome: string;
  result: string;
  summary: string;
  businessType: BusinessType;
  marketPosition: MarketPosition;
  trustSensitive: boolean;
  objections: Objection[];
  countries: string[];
  keywords: string[];
  pdfFile: string;
}

export const useCases: UseCase[] = [
  // ── No time / capacity for SEO ──────────────────────────────────────────────
  {
    id: 'kinwell',
    company: 'Kinwell',
    industry: 'ICT / Telecom',
    painPattern: 'No time / capacity for SEO',
    headline: 'No capacity for SEO',
    outcome: 'Freed capacity',
    result: 'Went from zero SEO activity to consistent content output and ranking improvements without hiring additional staff.',
    summary: 'Kinwell is a Dutch ICT and communications partner for SMEs, providing connectivity, telecom, security, and modern workplace solutions. They had existing domain authority and in-house SEO knowledge but lacked the capacity to scale content in a competitive B2B ICT market. WP SEO AI automated their content and optimization workflow, letting them compete online without adding headcount.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: true,
    objections: [
      'We are too small for this kind of approach',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'busy', 'resource', 'team too small', 'bandwidth', 'no one available', 'health', 'wellness'],
    pdfFile: 'No capacity for SEO - Kinwell - Success case.pdf',
  },
  {
    id: 'roelands',
    company: 'Roelands Boomkwekerijen',
    industry: 'Agriculture / Nursery',
    painPattern: 'No time / capacity for SEO',
    headline: 'No time & capacity for SEO',
    outcome: 'Freed capacity',
    result: 'Built a full SEO presence for their nursery business while the team stayed focused on growing and selling plants.',
    summary: 'Roelands Boomkwekerijen is a tree nursery in Zundert, Noord-Brabant, founded in 1974, specializing in forest and hedge plants with 50% of sales exported to Germany, Denmark, the UK, and Switzerland. As a B2B wholesaler with no marketing team, they had zero online visibility. WP SEO AI handled SEO end-to-end, letting the owners focus on growing and selling plants while gaining traction in a niche international market.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'B2B sector, nobody searches for our services',
      'Our customers are not online',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'agriculture', 'nursery', 'plants', 'grower', 'horticulture'],
    pdfFile: 'No time & capacity - Roelands Boomkwekerijen - Success case.pdf',
  },
  {
    id: 'mydearbeer',
    company: 'My Dear Beer',
    industry: 'F&B / Retail',
    painPattern: 'No time / capacity for SEO',
    headline: 'Too little time for SEO',
    outcome: 'Freed capacity',
    result: 'Grew organic webshop traffic significantly while the small team kept running day-to-day retail operations.',
    summary: 'My Dear Beer is an online specialty craft beer store in Nijmegen offering curated subscriptions, gift boxes, and rare brews, with both B2C and B2B corporate gifting channels. As a small team juggling curation, sustainable packaging, and bicycle delivery, they had no time for SEO. WP SEO AI automated product page optimization and content creation, driving organic traffic growth to the webshop.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We are too small for this kind of approach',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'food', 'beverage', 'retail', 'drinks', 'beer', 'ecommerce', 'webshop'],
    pdfFile: 'Too little time for SEO  - My Dear Beer - Success case.pdf',
  },
  {
    id: 'verdonk',
    company: 'Autobedrijven Verdonk',
    industry: 'Automotive',
    painPattern: 'No time / capacity for SEO',
    headline: 'Too little time for SEO',
    outcome: 'Freed capacity',
    result: 'Achieved consistent local search visibility across multiple dealership locations without dedicating internal staff to marketing.',
    summary: 'Autobedrijven Verdonk is a family-run used car dealership in Veldhoven with over 95 years of history, specializing in French brands like Renault, Peugeot, and Citroen. With no marketing team and a legacy reputation built offline, they had no time for SEO. WP SEO AI optimized their local presence and content, driving leads while the team focused on selling cars.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
      'We get everything from word of mouth',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'automotive', 'car', 'cars', 'dealer', 'garage', 'vehicles'],
    pdfFile: 'Too little time for SEO - Autobedrijven Verdonk - Success case.pdf',
  },
  {
    id: 'searchx',
    company: 'SearchX',
    industry: 'Agency',
    painPattern: 'No time / capacity for SEO',
    headline: 'Too little time for SEO',
    outcome: 'Freed capacity',
    result: 'Scaled SEO delivery for their clients without proportionally growing the team, improving margins per client.',
    summary: 'SearchX is a Dutch SEO agency providing organic traffic growth through technical SEO, content strategy, and link building with a small team. They struggled to scale delivery across their client base without proportionally growing headcount. WP SEO AI became their white-label execution layer, letting them serve more clients with the same team size and improving margins per client.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'Our sector is too technical or complex for AI content',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'agency', 'marketing agency', 'seo agency', 'white label'],
    pdfFile: 'Too little time for SEO - SearchX - Success case.pdf',
  },
  {
    id: 'berendijk',
    company: 'Timmerbedrijf Berendijk',
    industry: 'Construction',
    painPattern: 'No time / capacity for SEO',
    headline: 'Too little time for SEO',
    outcome: 'Freed capacity',
    result: 'Went from invisible online to ranking for key local construction searches, generating inbound leads for the first time.',
    summary: 'Timmerbedrijf Berendijk is a small Dutch construction and carpentry firm that relied entirely on word of mouth with zero online presence. They had no time or expertise to build a digital channel. WP SEO AI automated their local SEO and content, opening a new inbound lead channel for the first time.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'Our customers are not online',
      'We get everything from word of mouth',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'construction', 'building', 'contractor', 'timber'],
    pdfFile: 'Too little time for SEO - Timmerbedrijf Berendijk - Success case.pdf',
  },

  // ── Underperforming agency / high SEO cost ─────────────────────────────────
  {
    id: 'eleven',
    company: 'ELEVEN',
    industry: 'Music / Artist Management',
    painPattern: 'Underperforming agency / high SEO cost',
    headline: 'Underperforming agency, no in-house team, AI search advantage',
    outcome: 'Replaced agency, AI search advantage',
    result: 'Replaced their underperforming agency, cut costs, and gained early visibility in AI search results like ChatGPT.',
    summary: 'ELEVEN is a boutique music artist management and talent development agency based near Nijmegen, helping a curated roster of artists grow their careers. With no in-house marketing team and an external agency that wasn\'t delivering, WP SEO AI replaced the agency entirely — providing better results at lower cost while positioning them for AI search visibility.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['agency', 'underperforming', 'bad agency', 'no results', 'expensive', 'no marketing team', 'ai search', 'in-house'],
    pdfFile: 'Underperforming Agency - AI Search - No Inhouse Marketing Team -ELEVEN - .pdf',
  },
  {
    id: 'vleesandco',
    company: 'Vlees & Co',
    industry: 'F&B / Premium Dining',
    painPattern: 'Underperforming agency / high SEO cost',
    headline: 'Underperforming agency',
    outcome: 'Replaced agency',
    result: 'Transitioned away from an expensive agency to an AI-driven approach with better content quality and consistency.',
    summary: 'Vlees & Co is a premium steakhouse chain with locations in Arnhem, Nijmegen, and Amsterdam, serving high-quality steaks including USA Prime and Japanese Wagyu as official partners of the World Steak Challenge. Their SEO agency was delivering poor results despite high fees, so WP SEO AI replaced the agency — producing more relevant content faster and at a fraction of the cost.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
      'B2B sector, nobody searches for our services',
    ],
    countries: ['Netherlands'],
    keywords: ['agency', 'underperforming', 'bad agency', 'food', 'meat', 'wholesale'],
    pdfFile: 'Underperforming agency - Vlees & Co  - Success case .pdf',
  },
  {
    id: 'broekman',
    company: 'Broekman',
    industry: 'Premium Menswear / Retail',
    painPattern: 'Underperforming agency / high SEO cost',
    headline: 'High SEO cost with limited impact',
    outcome: 'Reduced cost, better results',
    result: 'Cut SEO spend significantly while achieving more traffic and conversions than the previous expensive agency setup.',
    summary: 'Broekman is a multi-generational premium menswear retailer founded in 1808, with stores in Utrecht and Huissen carrying brands like Polo Ralph Lauren, Lardini, and Incotex plus made-to-measure tailoring. They were paying high agency fees for SEO with minimal ROI. WP SEO AI delivered better traffic and conversions at a fraction of the cost.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
      'We already do Google Ads, why also SEO',
    ],
    countries: ['Netherlands'],
    keywords: ['expensive', 'cost', 'high cost', 'roi', 'agency', 'retail', 'limited impact', 'wasting money'],
    pdfFile: 'High SEO cost with limited impact - Broekman - Success case - Retail .pdf',
  },

  // ── AI / LLM search opportunity ────────────────────────────────────────────
  {
    id: 'kruijdenberg',
    company: 'Kruijdenberg',
    industry: 'Healthcare / Physiotherapy',
    painPattern: 'AI / LLM search opportunity',
    headline: 'AI curiosity & LLM search advantage',
    outcome: 'LLM search visibility',
    result: 'Became one of the first in their industry to appear in ChatGPT and AI search results, capturing early-mover advantage.',
    summary: 'Kruijdenberg is a Dutch physiotherapy and fitness centre (Centrum voor Fysiotherapie en Fysiofit), run by Kasper Kruijdenberg, with a knowledge-driven website covering movement, fitness, injuries, and recovery. As an early adopter curious about generative search, WP SEO AI structured their expertise content for LLM visibility, resulting in early presence in AI-generated answers.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'B2B sector, nobody searches for our services',
      'Our sector is too technical or complex for AI content',
    ],
    countries: ['Netherlands'],
    keywords: ['ai', 'llm', 'chatgpt', 'ai search', 'ai overviews', 'future', 'innovation', 'curious', 'industrial', 'manufacturing'],
    pdfFile: 'Ai curiosity & LLM search advantage - Kruijdenberg - Success case.pdf',
  },
  {
    id: 'wijzijntop',
    company: 'Wijzijntop',
    industry: 'Staffing / HR',
    painPattern: 'AI / LLM search opportunity',
    headline: 'AI curiosity but no strategy',
    outcome: 'AI strategy implemented',
    result: 'Went from AI-curious to having a structured AI search strategy with measurable visibility in LLM results.',
    summary: 'Wijzijntop Personeelsdiensten is a Dutch staffing agency based in Leek, Groningen, specializing in production, industry, engineering, logistics, and finance roles. With zero SEO experience and no marketing department, they relied entirely on referrals. WP SEO AI built their content strategy targeting CAO wage rates and temp work regulations, ranking them above FNV (major Dutch trade union) for competitive searches.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['ai', 'llm', 'chatgpt', 'strategy', 'no plan', 'ai search', 'direction'],
    pdfFile: 'AI curiosity but no strategy - Wijzijntop- Success case.pdf',
  },
  {
    id: 'catermonkey',
    company: 'Catermonkey',
    industry: 'SaaS / Catering Tech',
    painPattern: 'AI / LLM search opportunity',
    headline: 'Insane lead flow from ChatGPT & other LLMs',
    outcome: 'Lead flow from LLMs',
    result: 'Generated a significant new lead stream directly from ChatGPT and other LLM platforms, a channel competitors hadn\'t tapped.',
    summary: 'Catermonkey is a Dutch-Belgian all-in-one SaaS platform for party professionals and catering companies, covering event management, quotes, kitchen administration, invoicing, and payments — with 1,000+ customers across the Benelux and expanding internationally. WP SEO AI optimized their content for LLM discoverability, generating 60-70 blog leads including 7 directly from ChatGPT and one customer via Perplexity.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['ai', 'llm', 'chatgpt', 'leads', 'lead generation', 'catering', 'food', 'events'],
    pdfFile: 'Insane lead flow from Chat-gpt & other LLM_s - Catermonkey - Success case.pdf',
  },

  // ── Relied on single channel ───────────────────────────────────────────────
  {
    id: 'vandenakker',
    company: 'Autobedrijf Van den Akker',
    industry: 'Automotive',
    painPattern: 'Relied on single channel',
    headline: 'Relied on word of mouth',
    outcome: 'Diversified acquisition',
    result: 'Built a consistent online lead channel alongside word-of-mouth, reducing dependency on referrals alone.',
    summary: 'Autobedrijf Van den Akker is an official Honda dealership in Veghel, North Brabant, founded in 1982 and a Honda dealer since 1987. As a single-location SMB, they depended entirely on word of mouth for new customers. WP SEO AI built their organic search presence from scratch, creating a second acquisition channel that generates leads independently.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We get everything from word of mouth',
      'Our customers are not online',
    ],
    countries: ['Netherlands'],
    keywords: ['word of mouth', 'referral', 'one channel', 'single channel', 'automotive', 'car', 'dealer'],
    pdfFile: 'Relied on word of mouth - Autobedrijf Van den Akker - Success case.pdf',
  },
  {
    id: 'schulte-wom',
    company: 'Schulte Energie & Techniek',
    industry: 'Energy / Installation',
    painPattern: 'Relied on single channel',
    headline: 'Relied on word of mouth',
    outcome: 'Diversified acquisition',
    result: 'Opened an organic search channel that now generates leads alongside their existing referral network.',
    summary: 'Schulte Energie & Techniek is an installation company in Denekamp, Twente, with 30+ years of experience and over 10,000 solar systems installed, also offering heat pumps, home batteries, and charging stations. They relied solely on word of mouth for new business. WP SEO AI created an online presence that attracts customers outside their existing referral network.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We get everything from word of mouth',
      'Niche market, too specific for online marketing',
      'Our customers are not online',
    ],
    countries: ['Netherlands'],
    keywords: ['word of mouth', 'referral', 'energy', 'sustainability', 'green', 'solar', 'techniek', 'installation', 'hvac', 'heating', 'renewable'],
    pdfFile: 'Relied on word of mouth - Schulte Energie & Techniek - Success case.pdf',
  },
  {
    id: 'ckactive',
    company: 'CK Active',
    industry: 'Sports / Fitness',
    painPattern: 'Relied on single channel',
    headline: 'Relied heavily on SEA / Google Ads',
    outcome: 'Reduced SEA dependency',
    result: 'Reduced Google Ads spend while maintaining lead volume by building an organic search foundation.',
    summary: 'CK Active is a boutique personal training and private gym studio in Made, Noord-Brabant, offering customized training plans. They were spending heavily on Google Ads with no organic presence to fall back on. WP SEO AI built their SEO foundation so they could reduce ad spend without losing leads.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We already do Google Ads, why also SEO',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['google ads', 'sea', 'paid', 'ads', 'advertising', 'ppc', 'adwords', 'ad spend', 'sports', 'fitness'],
    pdfFile: 'Relied heaviliy on SEA - CK Active - Success case.pdf',
  },

  // ── Lack of control / visibility ───────────────────────────────────────────
  {
    id: 'sillegallery',
    company: 'Sille Gallery',
    industry: 'Retail / Art',
    painPattern: 'Lack of control / visibility',
    headline: 'Lack of control over SEO',
    outcome: 'Gained SEO control',
    result: 'Gained full visibility into their SEO performance and took control of their search strategy for the first time.',
    summary: 'Sille Gallery is a 450m2 contemporary art gallery in Oudewater representing over 250 Dutch artists, founded in 2007 by Tamara Sille and active at the Affordable Art Fair. They had no insight into their SEO performance or search visibility. WP SEO AI gave them clear dashboards and hands-on control over their search strategy for the first time.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'We tried it before and it didn\'t work',
    ],
    countries: ['Netherlands'],
    keywords: ['control', 'visibility', 'art', 'gallery', 'retail', 'no insight', 'dashboard', 'reporting'],
    pdfFile: 'Lack of Control Over SEO - Sille Gallery - Success case.pdf',
  },
  {
    id: 'cooffice',
    company: 'Co-Office',
    industry: 'Real Estate / Flex Office',
    painPattern: 'Lack of control / visibility',
    headline: 'Traffic drop during site transition',
    outcome: 'Recovered from traffic drop',
    result: 'Fully recovered organic traffic after a website migration that had caused a severe rankings drop.',
    summary: 'Co-Office is a flex office and coworking space in Amsterdam\'s Keynes Building, offering offices from 20 to 140m2 with digital locks and community networking events. They lost significant traffic during a website migration. WP SEO AI identified the technical issues, rebuilt their content strategy, and fully recovered their rankings.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
    ],
    countries: ['Netherlands'],
    keywords: ['traffic drop', 'migration', 'site transition', 'new website', 'relaunch', 'real estate', 'office', 'coworking', 'flex'],
    pdfFile: 'Traffic drop during site transition - Co-Office - Success case.pdf',
  },

  // ── Going international / scaling ──────────────────────────────────────────
  {
    id: 'geldzo',
    company: 'GeldZo',
    industry: 'Finance / Fintech',
    painPattern: 'Going international / scaling',
    headline: 'No time for manual work and going international',
    outcome: 'International SEO',
    result: 'Launched SEO in multiple new markets simultaneously without expanding the marketing team.',
    summary: 'GeldZo is a niche online-first financial administration service for ex-entrepreneurs with Dutch holding/BV structures such as Pension BVs and Annuity BVs, rated 8.9/10 across nearly 2,500 reviews. Expanding internationally, they could not scale manual SEO across languages. WP SEO AI automated multilingual content and optimization, enabling market entry in multiple countries at once.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: true,
    objections: [
      'It takes too long before you see results',
      'We are too small for this kind of approach',
    ],
    countries: ['Netherlands', 'International'],
    keywords: ['international', 'global', 'expand', 'multilingual', 'multiple countries', 'finance', 'fintech', 'scaling'],
    pdfFile: 'No time for manual work and going international - GeldZo - Success Case .pdf',
  },
  {
    id: 'pbn',
    company: 'PBN',
    industry: 'Professional Services',
    painPattern: 'Going international / scaling',
    headline: 'No time for manual work and going international',
    outcome: 'International SEO',
    result: 'Successfully scaled their SEO presence to new international markets while keeping the same lean team.',
    summary: 'PBN is a corporate events and outdoor team training company in Amsterdam with 40+ years of experience and 251-500 employees, organizing activities for groups of 20 to 600 people. Going international with limited marketing resources, they needed multilingual SEO at scale. WP SEO AI handled the execution so they could enter new markets without hiring local content teams.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We are too small for this kind of approach',
      'B2B sector, nobody searches for our services',
    ],
    countries: ['Netherlands', 'International'],
    keywords: ['international', 'global', 'expand', 'multilingual', 'multiple countries', 'scaling', 'professional services'],
    pdfFile: 'No time for manual work and going international - PBN - Success Case .pdf',
  },

  // ── Efficiency gap ─────────────────────────────────────────────────────────
  {
    id: 'officebox',
    company: 'Officebox',
    industry: 'IT / Managed Services',
    painPattern: 'Efficiency gap',
    headline: 'Efficiency gap',
    outcome: 'Efficiency gains',
    result: 'Automated SEO for thousands of product pages, eliminating hours of manual optimization work per week.',
    summary: 'Officebox is a managed IT services and cloud provider in Bunschoten-Spakenburg specializing in Microsoft 365 and Azure, with around 16 employees, over 20 years of experience, and approximately $3M in revenue. They faced an efficiency gap in their SEO process with no scalable way to optimize their online presence. WP SEO AI automated their content and optimization workflow, saving significant manual effort.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'It takes too long before you see results',
      'We already do Google Ads, why also SEO',
    ],
    countries: ['Netherlands'],
    keywords: ['efficiency', 'manual work', 'slow', 'time-consuming', 'office', 'supplies', 'b2b', 'product pages', 'catalog'],
    pdfFile: 'Efficiency gap - Officebox -.pdf',
  },
  {
    id: 'implicit',
    company: 'IMPLI-CIT',
    industry: 'IT / Software',
    painPattern: 'Efficiency gap',
    headline: 'Efficiency gap and new customers',
    outcome: 'Efficiency + new customers',
    result: 'Streamlined their content workflow and started attracting new customer segments through organic search.',
    summary: 'IMPLI-CIT is an IT managed services company founded in 1999 in Haarlem, specializing in onsite field technicians who travel across Europe, Asia, Africa, and the Americas for global IT companies. They were spending too much time on manual SEO tasks with limited results. WP SEO AI made their process efficient and opened up new customer acquisition channels they had not reached before.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'B2B sector, nobody searches for our services',
      'Our sector is too technical or complex for AI content',
    ],
    countries: ['Netherlands'],
    keywords: ['efficiency', 'new customers', 'growth', 'manual', 'leads', 'it', 'software', 'tech'],
    pdfFile: 'Efficiency gap and new customers - IMPLI-CIT - Success case.pdf',
  },

  // ── Limited marketing capacity ─────────────────────────────────────────────
  {
    id: 'dercsalotech',
    company: 'DERC Salotech',
    industry: 'Industrial / Tech',
    painPattern: 'Limited marketing capacity',
    headline: 'From limited marketing capacity to AI-ready SEO',
    outcome: 'AI-ready SEO',
    result: 'Built a complete AI-ready SEO strategy from scratch despite having no dedicated marketing resources.',
    summary: 'DERC Salotech is a manufacturer of high-pressure water jetting equipment in Oud-Beijerland, serving 55+ countries over 40 years with robotic systems for tank and pipe maintenance. With no marketing team and zero SEO foundation, they needed a full search strategy built from scratch. WP SEO AI built their entire search presence from the ground up, including AI search readiness, with minimal input needed from the client.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'B2B sector, nobody searches for our services',
      'Our sector is too technical or complex for AI content',
      'We are too small for this kind of approach',
    ],
    countries: ['Netherlands'],
    keywords: ['limited marketing', 'small team', 'no marketer', 'industrial', 'manufacturing', 'tech', 'b2b', 'ai-ready'],
    pdfFile: 'From limited marketing capacity to AI-ready SEO - DERC Salotech - Success Case - .pdf',
  },
  {
    id: 'schulte-scale',
    company: 'Schulte Energie & Techniek',
    industry: 'Energy / Installation',
    painPattern: 'Limited marketing capacity',
    headline: 'Limited capacity to scale for AI',
    outcome: 'Scaled for AI',
    result: 'Scaled their marketing output for AI search readiness without growing the team.',
    summary: 'Schulte Energie & Techniek is an installation company in Denekamp, Twente, founded in 2010, with 30+ years of combined experience and over 10,000 solar systems installed alongside heat pumps, home batteries, and charging stations. They knew AI search was coming but lacked the marketing capacity to prepare. WP SEO AI automated their content scaling so they are positioned for the AI search shift.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'Our customers are not online',
      'We get everything from word of mouth',
      'We are too small for this kind of approach',
    ],
    countries: ['Netherlands'],
    keywords: ['limited marketing', 'scale', 'ai', 'energy', 'sustainability', 'green', 'solar', 'techniek', 'installation', 'hvac', 'heating', 'renewable'],
    pdfFile: 'Schulte Energie & Techniek - Limited Capacity to Scale for AI .pdf',
  },

  // ── Other ──────────────────────────────────────────────────────────────────
  {
    id: 'kwiz',
    company: 'KWIZ',
    industry: 'Public Sector / Research',
    painPattern: 'Other',
    headline: 'New website & didn\'t like SEO copywriter',
    outcome: 'Replaced copywriter',
    result: 'Replaced an expensive SEO copywriter with AI-generated content that better matched their brand voice and converted better.',
    summary: 'KWIZ is a research bureau and information management consultancy for the social domain, based in Groningen and Amersfoort, processing public sector data into policy dashboards. They launched a new website but the SEO copywriter produced generic, low-quality content that did not match their specialized positioning. WP SEO AI delivered brand-aligned content at scale with better quality and significantly lower cost.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
    ],
    countries: ['Netherlands'],
    keywords: ['copywriter', 'content', 'new website', 'writing', 'copy', 'quality', 'entertainment', 'leisure'],
    pdfFile: 'New website & didnt like SEO copy writer - KWIZ Success Case - NL -  .pdf',
  },
  {
    id: 'ctalents',
    company: 'CTalents',
    industry: 'Inclusive Recruitment / Social Enterprise',
    painPattern: 'Other',
    headline: 'Struggled to keep up with developments in search behaviour',
    outcome: 'Kept up with search evolution',
    result: 'Stayed ahead of changing search behaviour patterns, maintaining visibility as candidates shifted how they search.',
    summary: 'CTalents is a social enterprise staffing agency in Amsterdam placing blind, visually impaired, deaf, hard-of-hearing, and autistic professionals, with a 90% retention rate and clients including ABN AMRO, ING, and Utrecht University. They struggled to keep up as candidate and employer search behaviour evolved rapidly. WP SEO AI kept their content strategy current with the latest search trends, including AI-driven search.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'It takes too long before you see results',
      'B2B sector, nobody searches for our services',
    ],
    countries: ['Netherlands'],
    keywords: ['search behaviour', 'changing landscape', 'keep up', 'recruitment', 'staffing', 'hr', 'talent'],
    pdfFile: 'Struggled to keep up with developments in search behaviour - CTalents - Success Case.pdf',
  },

  // ── New cases (April 2026) ─────────────────────────────────────────────────
  {
    id: 'ebikesde',
    company: 'ebikes.de',
    industry: 'E-commerce / Consumer Media',
    painPattern: 'No time / capacity for SEO',
    headline: 'Efficiency gap — strong domain but no time for content at scale',
    outcome: '+24,220% AI content traffic growth',
    result: '240 AI-optimized articles published in 9 months. +12,031 AI-attributed clicks, 1.25M impressions, traffic worth valued at €8,769. Content cited in ChatGPT and Google AI Overviews.',
    summary: 'ebikes.de is a German price comparison and editorial portal for e-bikes, offering deals, test reports, and buying guides through an affiliate and media model. With strong domain authority but a tiny team juggling research, content, and optimization, they could not scale. WP SEO AI scaled content production across key keyword clusters, driving massive organic and AI search growth.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'It takes too long before you see results',
      'We are too small for this kind of approach',
    ],
    countries: ['Germany'],
    keywords: ['e-bikes', 'ecommerce', 'ebike', 'german', 'germany', 'content at scale', 'ai overviews', 'chatgpt', 'consumer'],
    pdfFile: 'Efficiency Gap - e-bikes.de - Success case (ENGLISH).pdf',
  },
  {
    id: 'medici',
    company: 'Medici Vermittlung',
    industry: 'Healthcare / Medical Staffing',
    painPattern: 'Relied on single channel',
    headline: 'SEA budget fixed with SEO content — from paid dependency to organic growth',
    outcome: '+253% organic clicks, €10K traffic value',
    result: 'Organic clicks grew from 826 to 2,912 (+253%). Impressions up +551%. 82% of traffic from AI content. Visible in Google AI Overviews for key medical queries. Traffic worth €10,325.',
    summary: 'Medici Vermittlung is a German medical recruitment agency with 11-50 employees, placing physicians from assistant to chief level in permanent and locum roles. They had almost zero organic presence and unsustainable paid search costs. WP SEO AI published 196 articles in 5 months, fully automated, shifting acquisition from SEA to organic and AI search.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: true,
    objections: [
      'Trust-sensitive sector where mistakes are not allowed',
      'B2B sector, nobody searches for our services',
      'We already do Google Ads, why also SEO',
      'We are too small for this kind of approach',
    ],
    countries: ['Germany'],
    keywords: ['medical', 'healthcare', 'doctors', 'recruitment', 'staffing', 'sea', 'google ads', 'paid search', 'german', 'germany'],
    pdfFile: 'SEA budget fixed with SEO Content - Medici ENG - Success case (ENGLISH) .pdf',
  },
  {
    id: 'adelt-ideen',
    company: 'IP Adelt',
    industry: 'B2B / Visual Displays',
    painPattern: 'Lack of control / visibility',
    headline: 'No organic inbound acquisition — zero visibility to +470% growth',
    outcome: '+470% organic growth in 6 months',
    result: '+470% organic growth in 6 months (195 to 1,111 monthly clicks). 46.2% of clicks from AI content. Traffic worth €6,616. Featured in Google AI Overviews.',
    summary: 'IP Adelt is a German B2B manufacturer of custom promotional materials including sample cases, gift boxes, and display systems, based in Bielefeld with over 60 years of history and fully German-made sustainable production. They had zero organic acquisition and most product pages were not live. WP SEO AI built their organic channel from scratch, achieving +470% growth in 6 months.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'B2B sector, nobody searches for our services',
      'Niche market, too specific for online marketing',
      'Our customers are not online',
    ],
    countries: ['Germany'],
    keywords: ['visual displays', 'product presentation', 'b2b', 'german', 'germany', 'no organic', 'zero visibility', 'inbound'],
    pdfFile: 'No organic inbound acquisition - adelt-ideen.de - GERMAN  (1).pdf',
  },
  {
    id: 'quest-search',
    company: 'Quest Search and Selection',
    industry: 'Recruitment / HR',
    painPattern: 'Limited marketing capacity',
    headline: 'From marginal organic traffic to 775% growth and AI Overview dominance',
    outcome: '+775% organic traffic, €13.8K traffic value',
    result: '775% organic traffic growth. WP SEO AI share of clicks grew from 5% to 42%. +71K impressions/month. €13,828 traffic value. Now dominates Google AI Overviews with multiple articles per result.',
    summary: 'Quest Search and Selection is a UK specialist recruitment firm for Retail, FMCG, Leisure, and Travel, founded in 1994 in London with around 51 employees and a database of 800,000+ professionals. They knew SEO was key but lacked a content strategy to capitalize on it. WP SEO AI built and executed their entire organic content engine, growing them from marginal traffic to dominating AI Overviews in their niche.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'B2B sector, nobody searches for our services',
      'It takes too long before you see results',
    ],
    countries: ['United Kingdom'],
    keywords: ['recruitment', 'hr', 'staffing', 'search and selection', 'ai overviews', 'content strategy'],
    pdfFile: 'Quest search - Success case.pdf',
  },
  {
    id: 'greenstay',
    company: 'Greenstay',
    industry: 'Real Estate / Short-Stay Rentals',
    painPattern: 'Lack of control / visibility',
    headline: 'From zero SEO to 5x traffic and 100+ leads/month',
    outcome: '5x traffic, 100+ leads, 13% conversion rate',
    result: 'Organic traffic increased fivefold in 6 months. 100+ leads in August. 13% conversion rate vs 4% industry benchmark. Leads up +300%, cost of acquisition down -62%. Traffic worth €4,178.',
    summary: 'Greenstay is a small operator of furnished short-stay and corporate apartments in Amsterdam near Schiphol, listed on Booking.com. They had zero SEO efforts and no organic acquisition channel. WP SEO AI built their entire organic presence from scratch, achieving a conversion rate 3x the industry benchmark and dramatically lowering acquisition costs.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['short stay', 'housing', 'amsterdam', 'rental', 'real estate', 'leads', 'conversion', 'accommodation'],
    pdfFile: 'Greenstay - Success Case.pdf',
  },
  {
    id: 'salon-klipsi',
    company: 'Salon Klipsi',
    industry: 'Beauty / Personal Care',
    painPattern: 'No time / capacity for SEO',
    headline: 'Hair salon ranking #1 on Google with AI-powered SEO',
    outcome: '+57% organic traffic, #1 rankings',
    result: '+57% organic traffic in 8 months. +295% jump in top 3 rankings. Ranking #1 for high-intent terms. 41% of clicks from AI content. Scaled from 10 to 20+ articles/month.',
    summary: 'Salon Klipsi is a Finnish hair salon chain with 14 branches and around 60 hairdressers, founded in 1986, operating inside Sokos stores and Prisma supermarkets. Their clients were clearly searching on Google but the salon lacked time and SEO expertise across locations. WP SEO AI automated their content at scale, pushing them to #1 positions for high-intent local searches.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We are too small for this kind of approach',
      'Our customers are not online',
    ],
    countries: ['Finland'],
    keywords: ['salon', 'hair', 'beauty', 'finland', 'finnish', 'local seo', 'bookings', 'personal care'],
    pdfFile: 'Salon Klipsi - Success Case.pdf',
  },
  {
    id: 'moneybee',
    company: 'Moneybee',
    industry: 'B2B Financial Services / Accounting',
    painPattern: 'Limited marketing capacity',
    headline: '6-person accounting firm outranking national giants',
    outcome: '+372% organic traffic, €7.90 ROI per €1',
    result: '+372% organic traffic in 8 months. Outranking firms 20x their size. 90% of organic clicks from AI content. Every €1 spent earned €7.90 in CPC-equivalent traffic value. Leads grew fast enough to hire an additional colleague.',
    summary: 'Moneybee is a Finnish digital accounting firm for SMBs, founded in 2023 in Helsinki, offering revenue-based pricing through Procountor and Netvisor. As a 6-person company competing against national players with no marketing staff, they were invisible online. WP SEO AI turned them into an organic search powerhouse, outranking companies 20x their size and generating enough leads to hire additional staff.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: true,
    objections: [
      'We are too small for this kind of approach',
      'B2B sector, nobody searches for our services',
      'Trust-sensitive sector where mistakes are not allowed',
    ],
    countries: ['Finland'],
    keywords: ['accounting', 'finance', 'bookkeeping', 'finland', 'finnish', 'small business', 'b2b', 'roi'],
    pdfFile: 'Moneybee - Success Case.pdf',
  },
  {
    id: 'pest1',
    company: 'Pest1',
    industry: 'Home Services / Pest Control',
    painPattern: 'No time / capacity for SEO',
    headline: 'Pest control company quadruples organic traffic with AI content',
    outcome: '+339% organic growth, #1 in Google',
    result: '+339% organic traffic growth in less than a year. 95% of clicks from AI-optimized content. Ranking #1 in Google and featured in AI Overviews. Traffic worth €3,129. Seasonal content published proactively.',
    summary: 'Pest1 is a Finnish TUKES-licensed pest control company serving businesses, private individuals, and the public sector, with clients including hospitals and the Finnish Defence Forces. Despite search being critical for customer acquisition, they had low online visibility. WP SEO AI automated content production including proactive seasonal content, quadrupling their organic traffic.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'It takes too long before you see results',
      'Our customers are not online',
    ],
    countries: ['Finland'],
    keywords: ['pest control', 'home services', 'finland', 'finnish', 'seasonal', 'local', 'exterminator'],
    pdfFile: 'Pest1 Success Case.pdf',
  },
  {
    id: 'aimo-park',
    company: 'Aimo Park',
    industry: 'Mobility / Parking',
    painPattern: 'Lack of control / visibility',
    headline: '40-year brand invisible in non-branded search — now #1 with AI citations',
    outcome: '+203% non-branded clicks, ChatGPT citations',
    result: '+203% extra clicks in non-branded search. 1,500 extra clicks/month. #1 positions with featured snippets. Articles cited as source in ChatGPT responses for parking-related questions.',
    summary: 'Aimo Park is the largest Nordic parking operator with over 500,000 spaces across Sweden, Finland, and Norway, founded in 1959 in Stockholm and owned by Sumitomo Corporation, also operating car sharing and EV charging services. Despite 40+ years of history, they were completely invisible to anyone not already searching by brand name. WP SEO AI captured high-intent long-tail keywords, earning #1 positions and ChatGPT citations.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
      'It takes too long before you see results',
    ],
    countries: ['Sweden', 'Scandinavia'],
    keywords: ['parking', 'mobility', 'stockholm', 'scandinavia', 'sweden', 'brand', 'non-branded', 'chatgpt', 'featured snippets'],
    pdfFile: 'Aimo Park - Success Case.pdf',
  },
];

/** All unique pain patterns */
export const painPatterns = [...new Set(useCases.map((c) => c.painPattern))];

/** All unique industries */
export const industries = [...new Set(useCases.map((c) => c.industry))];

/** Objection counts — how many cases address each objection */
export const objectionCounts = OBJECTIONS.map((obj) => ({
  objection: obj,
  count: useCases.filter((c) => c.objections.includes(obj)).length,
}));
